### ISSUE TITLE
editing html tags automatically adds attributes to the closing html tag (which should never happen)

### ISSUE THREAD

**Issue by r6squeegee** [eclipse-lsp4e/lsp4e#114]
this has been happening to me for a while now, but specifically right now I'm on eclipse build 20220310-1457 
with "Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools	0.10.13.202204031849"

I'm on a blank line in an html file, and i type the following : 
`<div></div>`
     

What I really want is 
`<div class="foo"></div>`
though so I use the arrow keys to move back behind to the letter "v" and I press "space" and start typing the word "class". 

The editor starts adding that to the closing tag, i.e. I end up with
`<div class="foo"></div class="foo">`
 then I hit ctrl-z to undo and the editor completely screws up. i.e. it seems to randomly delete some characters and makes a complete mess of the surrounding lines of code. Basically I have to close the file with out saving and re-open it to get back to a sane state.

**Comment by angelozerr** [comment]
Are you sure that it is fixed for HTML? If yes it means HTML LS generate the same linked editing range than XML (which is fixed).

**Comment by r6squeegee** [comment]
it works for me
thanks!

**Comment by r6squeegee** [comment]
I think there might be a missed case in this fix.

It still happens on paste, i.e.
type:
`<div></div>`

and have 
` style="text-align:left"`

in your clipboard, move the cursor back to the div tag and press paste, causes 
`<div style="text-align:left"></div style="text-align:left">`

**Comment by vrubezhny** [comment]
Re-opened due to the copy-paste case - https://github.com/eclipse/lsp4e/issues/114#issuecomment-1123111703

**Comment by vrubezhny** [comment]
The upstream issue is opened https://github.com/eclipse-platform/eclipse.platform.text/issues/33 in order to track the copy-paste issue. The current API doesn't allow for adopters to exit the Linked Editing operation in case of pasting text that contains "stop" characters.

**Comment by sebthom** [comment]
@vrubezhny  I cannot reproduce this anymore. Can this issue be closed?
