### ISSUE TITLE
LSPFoldingReconcilingStrategy.applyFolding calls ProjectionViewer.postCatchupRequest way too many times

### ISSUE THREAD

**Issue by merks** [eclipse-lsp4e/lsp4e#1180]
I noticed the **very poor performance** editing a large *.target file, e.g., 

https://github.com/eclipse-orbit/orbit-simrel/blob/main/maven-bnd/tp/MavenBND.target

Here's what happens the first time I try to edit the document:

![image](https://github.com/user-attachments/assets/bd6169c4-cf29-4fa3-8eda-3e02bf2708e3)

It wants to add hundreds of folding regions and there already exist hundreds of them.

It ends up in here where it takes some completely arbitrary annotation and decides that one should be updated:

![image](https://github.com/user-attachments/assets/9c5ac639-607f-4b3e-b0f0-603c2e5df957)

There might well exist a folding annotation at the target position, but it chooses an arbitrary one to update and then ends up here:

![image](https://github.com/user-attachments/assets/fdfd2cbd-6b06-4f4b-b7cf-01f1347aa6cf)

That queues up an event that needs to be processed in the UI thread.

Eventually in the UI thread we see this:

![image](https://github.com/user-attachments/assets/efd9e645-c425-4f86-82cb-997acaf8598d)

I.e., hundreds of events to process, each one calling this for a PDE *.target document:

![image](https://github.com/user-attachments/assets/0a3ca9c8-869b-4009-a5bf-3c04986463ad)

So the UI is frozen for way way too long.  This happens even in a Generic Editor.

If I hack the implementation to simply send in a empty `bogus` list to the updateAnnotation call, then it creates all new annotations and at the end it will simply remove all the existing ones and add all the new ones, which is handled with a single event.

![image](https://github.com/user-attachments/assets/45afca72-a981-492b-b32a-117c72045963)

I think the other approach would be to build a map for `existing` from Position to annotation so that one would avoid removing adding annotations that already properly exist at the given position.  But that would require a signature change for org.eclipse.lsp4e.operations.folding.LSPFoldingReconcilingStrategy.markInvalidAnnotationsForDeletion(List<FoldingAnnotation>, List<FoldingAnnotation>) which is protected.  So I'm not sure how best to fix this.  I suppose we could also fetch the positions twice to avoid API changes.

I'll await your feedback to determine the best course of action.

**Comment by sebthom** [comment]
could it be that you are running a relatively old version of LSP4E? I think this has been already addressed last February in https://github.com/eclipse-lsp4e/lsp4e/pull/933

The source code screenshots don't match what is in SCM: 
https://github.com/eclipse-lsp4e/lsp4e/blob/944144edc5955aa666cdacde01312792af45b6ef/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java#L179-L220

**Comment by merks** [comment]
It's the current released version:

![image](https://github.com/user-attachments/assets/c22c99c5-1560-4f62-9d23-f7a464f88648)

The source does look a little different.  In any case, I expect the behavior remains the same because this is where some arbitrary existing annotation is updated and that its what's generating the huge number of calls to postCatchupRequest:

https://github.com/eclipse-lsp4e/lsp4e/blob/944144edc5955aa666cdacde01312792af45b6ef/org.eclipse.lsp4e/src/org/eclipse/lsp4e/operations/folding/LSPFoldingReconcilingStrategy.java#L280-L293

**Comment by merks** [comment]
Yes, I've verified that definitely the problem is still the same.

**Comment by sebthom** [comment]
Regarding your suggestions, I would prefer your second approach, so the correct annotation is updated instead of a random one. I couldn't find any references to markInvalidAnnotationsForDeletion in any other github repo. I would suggest we reduce the visibility of markInvalidAnnotationsForDeletion and updateAnnotations to private and adjust the signature as needed. I guess it was an oversight that they are protected.

@rubenporras @mickaelistria WDYT?

**Comment by rubenporras** [comment]
I am happy with reducing the visibility of markInvalidAnnotationsForDeletion and updateAnnotations to private and adjust the signature as needed.

**Comment by merks** [comment]
Here is one possible solution using a map:

![image](https://github.com/user-attachments/assets/54b91028-b678-4910-9176-c7792ca9c5d6)

We could change this method to compute a map:

![image](https://github.com/user-attachments/assets/9b404317-6188-483e-88da-839a7bd3e63b)

We can be careful that there are not multiple annotations at the same position, which probably can't happen, but better safe than sorry.

This works well.  Note that we never update an annotation because if the annotation exists at that position, we don't need to do anything because the existing annotation is correct.  And while debugging the common case is that we do not need to do anything and we might want to optimize the case where deletions and additions are both empty:

![image](https://github.com/user-attachments/assets/08e7f379-ea78-4b13-9869-5504ef2d977b)

**Comment by merks** [comment]
Given the feedback so far, I will create a PR with a proposal.  Thanks for the quick feedback!!  😃
